// 以下 7 条规则 dae 不支持，已跳过
// PROCESS-NAME,Tencent Lemon
// PROCESS-NAME,LemonMonitor
// PROCESS-NAME,LemonDaemon
// PROCESS-NAME,LemonAgent
// PROCESS-NAME,LemonService
// DEST-PORT,7680
// AND,((DOMAIN-KEYWORD,genuine), (DOMAIN-KEYWORD,autodesk))
