// 以下 10 条规则 dae 不支持，已跳过
// USER-AGENT,FOX NOW*
// USER-AGENT,FOXPlus*
// USER-AGENT,Hulu*
// USER-AGENT,encoreTVB*
// USER-AGENT,TVer-Release*
// USER-AGENT,DPlus*
// USER-AGENT,discovery+*
// USER-AGENT,PPlus*
// USER-AGENT,PeacockMobile*
// PROCESS-NAME,com.hulu.plus
