name: Build dae dat


on:

  schedule:

    - cron: "0 3 */3 * *"


  workflow_dispatch:



permissions:

  contents: write



jobs:


  build:


    runs-on: ubuntu-latest



    steps:


    - name: Checkout

      uses: actions/checkout@v4



    - name: Download Sukka rules

      uses: actions/checkout@v4

      with:

        repository: SukkaLab/ruleset.skk.moe

        path: ruleset



    - name: Setup Go

      uses: actions/setup-go@v5

      with:

        go-version: stable



    - name: Convert rules

      run: |

        python3 scripts/convert_sukka.py



    - name: Build geosite.dat

      run: |

        mkdir release


        git clone \
        https://github.com/v2fly/domain-list-community.git


        cp -r data \
        domain-list-community/data



        cd domain-list-community


        go install .


        $(go env GOPATH)/bin/domain-list-community \
        -outputdir ../release \
        -outputname geosite.dat



    - name: Build geoip.dat

      run: |

        git clone \
        https://github.com/v2fly/geoip.git



        cp -r geoip_data \
        geoip/data



        cd geoip


        go install .


        $(go env GOPATH)/bin/geoip \
        -outputdir ../release \
        -outputname geoip.dat



    - name: Release

      uses: softprops/action-gh-release@v2

      with:

        tag_name: latest

        files: |

          release/geosite.dat

          release/geoip.dat
