name: Convert Sukka Surge Rules to dae

on:

  # 手动运行
  workflow_dispatch:

  # 每3天运行一次
  schedule:
    - cron: "0 3 */3 * *"


permissions:
  contents: write


jobs:

  convert:

    runs-on: ubuntu-latest


    steps:


      # 拉取当前仓库
      - name: Checkout repository
        uses: actions/checkout@v4



      # Python环境
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"



      # 执行转换
      - name: Convert rules
        run: |

          python3 convert.py



      # 提交变化
      - name: Commit changes
        run: |

          git config user.name \
            "github-actions[bot]"

          git config user.email \
            "41898282+github-actions[bot]@users.noreply.github.com"


          git add output/


          if git diff \
             --cached \
             --quiet;

          then

              echo "No changes"

              exit 0

          fi


          git commit \
            -m "Auto update dae rules"


          git push
